import { useReducer } from "react";
import { MainContext, initialstate } from "@/state";
import { mainReducer } from "@/state/reducers";
import Head from "next/head";
import Todo from "@/components/todo";
import Task from "@/components/task";
import Login from "@/components/login";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  const [state, dispatch] = useReducer(mainReducer, initialstate);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContext.Provider value={{ state, dispatch }}>
        <main>
          <h1>Todo list - {state.user}</h1>
          {state.user ? <Todo /> : <Login />}
        </main>
      </MainContext.Provider>
    </>
  );
}
